using FluentAssertions;
using Microsoft.CodeAnalysis;

namespace RoyalCode.SmartSelector.Tests.Tests;

public class AutoDetailsTests1
{
    [Fact]
    public void Generate_Details_Class_For_Nested_Property_With_AutoDetails()
    {
        var result = Util.CompileAndAssert(Code.Types);

        var generatedDetails = result.GeneratedSource("Tests.SmartSelector.Models.AddressDetails.AutoDetails.g.cs");
        generatedDetails.Should().Be(Code.ExpectedDetailsClass);

        var generatedPartial = result.GeneratedSource("Tests.SmartSelector.Models.CustomerDetails.AutoSelect.g.cs");
        generatedPartial.Should().Be(Code.ExpectedPartial);

        var generatedExtensions = result.GeneratedSource("Tests.SmartSelector.Models.CustomerDetails.Extensions.g.cs");
        generatedExtensions.Should().Be(Code.ExpectedExtension);
    }
}

file static class Code
{
    public const string Types =
    """
using RoyalCode.SmartSelector;
using System;

namespace Tests.SmartSelector.Models;

#nullable disable // poco

public class Address
{
    public string City { get; set; }
    public string Zip  { get; set; }
    public string Street { get; set; }
}

public class Customer
{
    public Guid Id { get; set; }
    public Address Address { get; set; }
}

// Propriedade Address decorada com AutoDetails deve gerar classe AddressDetails com as propriedades simples de Address
[AutoSelect<Customer>, AutoProperties]
public partial class CustomerDetails
{
    [AutoDetails]
    public AddressDetails Address { get; set; }
    public Guid Id { get; set; }
}
""";

    public const string ExpectedDetailsClass =
    """
// <auto-generated/>
#nullable enable annotations

using System;
using System.Linq;
using System.Collections.Generic;

namespace Tests.SmartSelector.Models;

/// <summary>Generated details class, projected from the source type.</summary>
[global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
public partial class AddressDetails
{
    /// <summary>Generated property, projected from the source type.</summary>
    public string City { get; set; }

    /// <summary>Generated property, projected from the source type.</summary>
    public string Zip { get; set; }

    /// <summary>Generated property, projected from the source type.</summary>
    public string Street { get; set; }
}

""";
    public const string ExpectedPartial =
    """
// <auto-generated/>
#nullable enable annotations

using System;
using System.Linq;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace Tests.SmartSelector.Models;

public partial class CustomerDetails
{
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    private static Func<Customer, CustomerDetails>? selectCustomerFunc;

    /// <summary>Projection expression that creates a new <see cref="CustomerDetails"/> from a <see cref="Customer"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    public static Expression<Func<Customer, CustomerDetails>> SelectCustomerExpression { get; } = a => new CustomerDetails
    {
        Address = new AddressDetails
        {
            City = a.Address.City,
            Zip = a.Address.Zip,
            Street = a.Address.Street
        },
        Id = a.Id
    };

    /// <summary>Creates a new <see cref="CustomerDetails"/> projected from a <see cref="Customer"/> instance.</summary>
    /// <param name="customer">The source instance to project.</param>
    /// <returns>A new <see cref="CustomerDetails"/> instance.</returns>
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    public static CustomerDetails From(Customer customer) => (selectCustomerFunc ??= SelectCustomerExpression.Compile())(customer);
}

""";
    public const string ExpectedExtension =
    """
// <auto-generated/>
#nullable enable annotations

using System;
using System.Linq;
using System.Collections.Generic;

namespace Tests.SmartSelector.Models;

/// <summary>Generated extension methods to project <see cref="Customer"/> instances into <see cref="CustomerDetails"/> instances.</summary>
[global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
public static class CustomerDetails_Extensions
{
    /// <summary>Projects the <see cref="Customer"/> query into <see cref="CustomerDetails"/>.</summary>
    /// <param name="query">The source query.</param>
    /// <returns>An <see cref="IQueryable{T}"/> of <see cref="CustomerDetails"/>.</returns>
    public static IQueryable<CustomerDetails> SelectCustomerDetails(this IQueryable<Customer> query)
    {
        return query.Select(CustomerDetails.SelectCustomerExpression);
    }

    /// <summary>Projects the <see cref="Customer"/> items into <see cref="CustomerDetails"/>.</summary>
    /// <param name="enumerable">The source items.</param>
    /// <returns>An <see cref="IEnumerable{T}"/> of <see cref="CustomerDetails"/>.</returns>
    public static IEnumerable<CustomerDetails> SelectCustomerDetails(this IEnumerable<Customer> enumerable)
    {
        return enumerable.Select(CustomerDetails.From);
    }

    /// <summary>Projects a <see cref="Customer"/> instance into a new <see cref="CustomerDetails"/>.</summary>
    /// <param name="customer">The source instance to project.</param>
    /// <returns>A new <see cref="CustomerDetails"/> instance.</returns>
    public static CustomerDetails ToCustomerDetails(this Customer customer) => CustomerDetails.From(customer);
}

""";
}
