using FluentAssertions;
using Microsoft.CodeAnalysis;

namespace RoyalCode.SmartSelector.Tests.Tests;

public class DeepFlatteningSelectorTests
{
    [Fact]
    public void Select_With_Deep_Flattened_Nested_Properties()
    {
        var result = Util.CompileAndAssert(Code.Types);

        var generatedPartial = result.GeneratedSource("Tests.SmartSelector.Models.OrderDetails.AutoSelect.g.cs");
        generatedPartial.Should().Be(Code.ExpectedPartial);

        var generatedExtensions = result.GeneratedSource("Tests.SmartSelector.Models.OrderDetails.Extensions.g.cs");
        generatedExtensions.Should().Be(Code.ExpectedExtension);
    }
}

file static class Code
{
    public const string Types =
"""
using RoyalCode.SmartSelector;
using System;

namespace Tests.SmartSelector.Models;

#nullable disable // poco

public class Region
{
    public string Name { get; set; }
}

public class Country
{
    public string Name { get; set; }
    public string Code { get; set; }
    public Region Region { get; set; }
}

public class Address
{
    public string Street { get; set; }
    public Country Country { get; set; }
}

public class Customer
{
    public Guid Id { get; set; }
    public Address Address { get; set; }
}

public class Order
{
    public Guid Id { get; set; }
    public Customer Customer { get; set; }
}

// Flatten esperado:
//   CustomerAddressCountryName           -> a.Customer.Address.Country.Name
//   CustomerAddressCountryCode           -> a.Customer.Address.Country.Code
//   CustomerAddressCountryRegionName     -> a.Customer.Address.Country.Region.Name
[AutoSelect<Order>]
public partial class OrderDetails
{
    public Guid Id { get; set; }
    public string CustomerAddressCountryName { get; set; }
    public string CustomerAddressCountryCode { get; set; }
    public string CustomerAddressCountryRegionName { get; set; }
}
""";

    public const string ExpectedPartial =
"""
// <auto-generated/>
#nullable enable annotations

using System;
using System.Linq;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace Tests.SmartSelector.Models;

public partial class OrderDetails
{
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    private static Func<Order, OrderDetails>? selectOrderFunc;

    /// <summary>Projection expression that creates a new <see cref="OrderDetails"/> from a <see cref="Order"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    public static Expression<Func<Order, OrderDetails>> SelectOrderExpression { get; } = a => new OrderDetails
    {
        Id = a.Id,
        CustomerAddressCountryName = a.Customer.Address.Country.Name,
        CustomerAddressCountryCode = a.Customer.Address.Country.Code,
        CustomerAddressCountryRegionName = a.Customer.Address.Country.Region.Name
    };

    /// <summary>Creates a new <see cref="OrderDetails"/> projected from a <see cref="Order"/> instance.</summary>
    /// <param name="order">The source instance to project.</param>
    /// <returns>A new <see cref="OrderDetails"/> instance.</returns>
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    public static OrderDetails From(Order order) => (selectOrderFunc ??= SelectOrderExpression.Compile())(order);
}

""";

    public const string ExpectedExtension =
"""
// <auto-generated/>
#nullable enable annotations

using System;
using System.Linq;
using System.Collections.Generic;

namespace Tests.SmartSelector.Models;

/// <summary>Generated extension methods to project <see cref="Order"/> instances into <see cref="OrderDetails"/> instances.</summary>
[global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
public static class OrderDetails_Extensions
{
    /// <summary>Projects the <see cref="Order"/> query into <see cref="OrderDetails"/>.</summary>
    /// <param name="query">The source query.</param>
    /// <returns>An <see cref="IQueryable{T}"/> of <see cref="OrderDetails"/>.</returns>
    public static IQueryable<OrderDetails> SelectOrderDetails(this IQueryable<Order> query)
    {
        return query.Select(OrderDetails.SelectOrderExpression);
    }

    /// <summary>Projects the <see cref="Order"/> items into <see cref="OrderDetails"/>.</summary>
    /// <param name="enumerable">The source items.</param>
    /// <returns>An <see cref="IEnumerable{T}"/> of <see cref="OrderDetails"/>.</returns>
    public static IEnumerable<OrderDetails> SelectOrderDetails(this IEnumerable<Order> enumerable)
    {
        return enumerable.Select(OrderDetails.From);
    }

    /// <summary>Projects a <see cref="Order"/> instance into a new <see cref="OrderDetails"/>.</summary>
    /// <param name="order">The source instance to project.</param>
    /// <returns>A new <see cref="OrderDetails"/> instance.</returns>
    public static OrderDetails ToOrderDetails(this Order order) => OrderDetails.From(order);
}

""";
}
