using FluentAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace RoyalCode.SmartSelector.Tests.Tests;

/// <summary>
/// Tests for the Phase 11 emission conventions: auto-generated header, nullable annotations,
/// [GeneratedCode] gradation (DF11) and XML docs on public generated members.
/// </summary>
public class GeneratedCodeConventionsTests
{
    private const string SimpleFixture =
        """
        using RoyalCode.SmartSelector;

        namespace Tests.SmartSelector.Conventions;

        #nullable disable // poco

        public class Product
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }

        [AutoSelect<Product>]
        public partial class ProductDetails
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }
        """;

    [Fact]
    public void Generated_files_should_start_with_the_auto_generated_header()
    {
        var result = Util.CompileAndAssert(SimpleFixture);

        result.GeneratedSources.Should().NotBeEmpty();
        foreach (var pair in result.GeneratedSources)
        {
            pair.Value.Should().StartWith(
                "// <auto-generated/>\r\n#nullable enable annotations\r\n",
                "file {0} must carry the generated header and nullable directive",
                pair.Key);
        }
    }

    [Fact]
    public void GeneratedCode_attribute_should_follow_the_DF11_gradation()
    {
        var result = Util.CompileAndAssert(SimpleFixture);

        // declaração partial do usuário: atributo somente nos membros, nunca no tipo
        var partial = result.GeneratedSource("Tests.SmartSelector.Conventions.ProductDetails.AutoSelect.g.cs");
        var beforeClass = partial.Substring(0, partial.IndexOf("public partial class", StringComparison.Ordinal));
        beforeClass.Should().NotContain("GeneratedCode");
        partial.Should().Contain("[global::System.CodeDom.Compiler.GeneratedCode(");

        // classe sem declaração do usuário: atributo no tipo
        var extensions = result.GeneratedSource("Tests.SmartSelector.Conventions.ProductDetails.Extensions.g.cs");
        var beforeExtensions = extensions.Substring(
            0, extensions.IndexOf("public static class", StringComparison.Ordinal));
        beforeExtensions.Should().Contain("[global::System.CodeDom.Compiler.GeneratedCode(");
    }

    [Fact]
    public void Cache_field_should_be_nullable()
    {
        var result = Util.CompileAndAssert(SimpleFixture);

        var partial = result.GeneratedSource("Tests.SmartSelector.Conventions.ProductDetails.AutoSelect.g.cs");
        partial.Should().Contain("private static Func<Product, ProductDetails>? selectProductFunc;");
    }

    [Fact]
    public void Nullable_reference_annotations_should_be_preserved_on_generated_properties()
    {
        var result = Util.CompileAndAssert(
            """
            using RoyalCode.SmartSelector;

            namespace Tests.SmartSelector.Conventions;

            public class Person
            {
                public int Id { get; set; }
                public string Name { get; set; } = string.Empty;
                public string? Nick { get; set; }
                public int? Age { get; set; }
            }

            [AutoProperties<Person>]
            public partial class PersonDetails { }

            public static class Consumer
            {
                public static string? Read(PersonDetails details) => details.Nick;
            }
            """);

        var generated = result.GeneratedSource("Tests.SmartSelector.Conventions.PersonDetails.AutoProperties.g.cs");
        generated.Should().Contain("public string Name { get; set; }");
        generated.Should().Contain("public string? Nick { get; set; }");
        generated.Should().Contain("public Int32? Age { get; set; }");
    }

    [Fact]
    public void Generated_public_members_should_not_produce_CS1591()
    {
        var parseOptions = new CSharpParseOptions(
            LanguageVersion.Preview,
            documentationMode: DocumentationMode.Diagnose);

        var trustedPlatformAssemblies = (string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")
            ?? throw new InvalidOperationException("The test host did not provide trusted platform assemblies.");
        var references = trustedPlatformAssemblies
            .Split(Path.PathSeparator)
            .Select(static path => MetadataReference.CreateFromFile(path))
            .Cast<MetadataReference>()
            .ToList();
        references.Add(MetadataReference.CreateFromFile(typeof(AutoSelectAttribute<>).Assembly.Location));

        var syntaxTree = CSharpSyntaxTree.ParseText(SimpleFixture, parseOptions);
        var compilation = CSharpCompilation.Create(
            "DocumentationTests",
            [syntaxTree],
            references,
            new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable));

        var driver = CSharpGeneratorDriver.Create(
            generators: [new Generators.IncrementalGenerator().AsSourceGenerator()],
            parseOptions: parseOptions);
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out _);

        var missingDocsInGeneratedCode = outputCompilation.GetDiagnostics()
            .Where(static diagnostic => diagnostic.Id == "CS1591")
            .Where(static diagnostic =>
                diagnostic.Location.SourceTree?.FilePath.EndsWith(".g.cs", StringComparison.Ordinal) == true)
            .ToList();

        missingDocsInGeneratedCode.Should().BeEmpty(
            "public generated members must carry XML docs; diagnostics:\n{0}",
            string.Join("\n", missingDocsInGeneratedCode));
    }
}
