using FluentAssertions;
using Microsoft.CodeAnalysis;

namespace RoyalCode.SmartSelector.Tests.Tests;

public partial class MapFromTests
{
    [Fact]
    public void Select_ProductDetails_With_MapFromAttribute()
    {
        var result = Util.CompileAndAssert(Code.Types);

        var generatedInterface = result.GeneratedSource("Tests.SmartSelector.Models.ProductDetails.AutoSelect.g.cs");
        generatedInterface.Should().Be(Code.ExpectedPartial);

        var generatedHandler = result.GeneratedSource("Tests.SmartSelector.Models.ProductDetails.Extensions.g.cs");
        generatedHandler.Should().Be(Code.ExpectedExtension);
    }
}

file static class Code
{
    public const string Types =
"""
using RoyalCode.SmartSelector;

namespace Tests.SmartSelector.Models;

#nullable disable // poco

public abstract class Entity<TId>
{
    public TId Id { get; protected set; }
}

public class Product : Entity<Guid>
{
    public Product(string name)
    {
        Name = name;
        Active = true;
    }
    public string Name { get; set; }
    public bool Active { get; set; }
}

[AutoSelect<Product>]
public partial class ProductDetails
{
    [MapFrom("Id")]
    public Guid CustomId { get; set; }
    
    [MapFrom(nameof(Product.Name))]
    public string CustomName { get; set; }

    [MapFrom(nameof(Product.Active))]
    public bool CustomActive { get; set; }
}
""";

    public const string ExpectedPartial =
"""
// <auto-generated/>
#nullable enable annotations

using System;
using System.Linq;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace Tests.SmartSelector.Models;

public partial class ProductDetails
{
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.3.0")]
    private static Func<Product, ProductDetails>? selectProductFunc;

    /// <summary>Projection expression that creates a new <see cref="ProductDetails"/> from a <see cref="Product"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.3.0")]
    public static Expression<Func<Product, ProductDetails>> SelectProductExpression { get; } = a => new ProductDetails
    {
        CustomId = a.Id,
        CustomName = a.Name,
        CustomActive = a.Active
    };

    /// <summary>Creates a new <see cref="ProductDetails"/> projected from a <see cref="Product"/> instance.</summary>
    /// <param name="product">The source instance to project.</param>
    /// <returns>A new <see cref="ProductDetails"/> instance.</returns>
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.3.0")]
    public static ProductDetails From(Product product) => (selectProductFunc ??= SelectProductExpression.Compile())(product);
}

""";

    public const string ExpectedExtension =
"""
// <auto-generated/>
#nullable enable annotations

using System;
using System.Linq;
using System.Collections.Generic;

namespace Tests.SmartSelector.Models;

/// <summary>Generated extension methods to project <see cref="Product"/> instances into <see cref="ProductDetails"/> instances.</summary>
[global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.3.0")]
public static class ProductDetails_Extensions
{
    /// <summary>Projects the <see cref="Product"/> query into <see cref="ProductDetails"/>.</summary>
    /// <param name="query">The source query.</param>
    /// <returns>An <see cref="IQueryable{T}"/> of <see cref="ProductDetails"/>.</returns>
    public static IQueryable<ProductDetails> SelectProductDetails(this IQueryable<Product> query)
    {
        return query.Select(ProductDetails.SelectProductExpression);
    }

    /// <summary>Projects the <see cref="Product"/> items into <see cref="ProductDetails"/>.</summary>
    /// <param name="enumerable">The source items.</param>
    /// <returns>An <see cref="IEnumerable{T}"/> of <see cref="ProductDetails"/>.</returns>
    public static IEnumerable<ProductDetails> SelectProductDetails(this IEnumerable<Product> enumerable)
    {
        return enumerable.Select(ProductDetails.From);
    }

    /// <summary>Projects a <see cref="Product"/> instance into a new <see cref="ProductDetails"/>.</summary>
    /// <param name="product">The source instance to project.</param>
    /// <returns>A new <see cref="ProductDetails"/> instance.</returns>
    public static ProductDetails ToProductDetails(this Product product) => ProductDetails.From(product);
}

""";
}
