using FluentAssertions;
using Microsoft.CodeAnalysis;

namespace RoyalCode.SmartSelector.Tests.Tests;

public partial class NullableAndCastSelectorTests
{
    [Fact]
    public void Select_Nulls_Ints()
    {
        var result = Util.CompileAndAssert(Code.Types);

        var generatedInterface = result.GeneratedSource("Tests.SmartSelector.Models.IntNullsDto.AutoSelect.g.cs");
        generatedInterface.Should().Be(Code.ExpectedPartial);
    }
}

file static class Code
{
    public const string Types =
"""
using RoyalCode.SmartSelector;

namespace Tests.SmartSelector.Models;

public class IntNulls
{
    public int Value1 { get; set; } = default!;
    public int Value2 { get; set; } = default!;
    public int? Value3 { get; set; }
    public int? Value4 { get; set; }
}

[AutoSelect<IntNulls>]
public partial class IntNullsDto
{
    public int Value1 { get; set; } = default!;
    public int? Value2 { get; set; }
    public int Value3 { get; set; } = default!;
    public int? Value4 { get; set; }
}

""";

    public const string ExpectedPartial =
"""
// <auto-generated/>
#nullable enable annotations

using System;
using System.Linq;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace Tests.SmartSelector.Models;

public partial class IntNullsDto
{
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.3.0")]
    private static Func<IntNulls, IntNullsDto>? selectIntNullsFunc;

    /// <summary>Projection expression that creates a new <see cref="IntNullsDto"/> from a <see cref="IntNulls"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.3.0")]
    public static Expression<Func<IntNulls, IntNullsDto>> SelectIntNullsExpression { get; } = a => new IntNullsDto
    {
        Value1 = a.Value1,
        Value2 = a.Value2,
        Value3 = a.Value3.HasValue ? a.Value3.Value : default,
        Value4 = a.Value4
    };

    /// <summary>Creates a new <see cref="IntNullsDto"/> projected from a <see cref="IntNulls"/> instance.</summary>
    /// <param name="intNulls">The source instance to project.</param>
    /// <returns>A new <see cref="IntNullsDto"/> instance.</returns>
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.3.0")]
    public static IntNullsDto From(IntNulls intNulls) => (selectIntNullsFunc ??= SelectIntNullsExpression.Compile())(intNulls);
}

""";
}
