using FluentAssertions;
using Microsoft.CodeAnalysis;

namespace RoyalCode.SmartSelector.Tests.Tests;

public partial class NullableAndCastSelectorTests
{
    [Fact]
    public void Select_UserDetails_CastAndNullable()
    {
        var result = Util.CompileAndAssert(Code.Types);

        var generatedInterface = result.GeneratedSource("Tests.SmartSelector.Models.UserDetails.AutoSelect.g.cs");
        generatedInterface.Should().Be(Code.ExpectedPartial);

        var generatedHandler = result.GeneratedSource("Tests.SmartSelector.Models.UserDetails.Extensions.g.cs");
        generatedHandler.Should().Be(Code.ExpectedExtension);
    }
}

file static class Code
{
    public const string Types =
"""
using RoyalCode.SmartSelector;

namespace Tests.SmartSelector.Models;

#nullable disable // poco

public abstract class Entity<TId>
{
    public TId Id { get; protected set; }
}

public class User : Entity<Guid>
{
    public User(string name)
    {
        Name = name;
        Status = Status.Active;
    }
    public string Name { get; set; }

    public Status Status { get; set; }

    public DateTimeOffset? LastLogin { get; set; }

    public UserSpecialization? Specialization { get; set; }
}

public enum Status
{
    Active,
    Inactive,
    Blocked,
    Suspended,
}

public enum UserSpecialization
{
    None,
    Developer,
    Designer,
    Manager,
    Tester,
}

[AutoSelect<User>]
public partial class UserDetails
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public StatusDetails Status { get; set; }
    public DateTimeOffset LastLogin { get; set; }
    public UserSpecializationDetails Specialization { get; set; }
}

public enum StatusDetails
{
    Active,
    Inactive,
    Blocked,
    Suspended,
}

public enum UserSpecializationDetails
{
    None,
    Developer,
    Designer,
    Manager,
    Tester,
}
""";

    public const string ExpectedPartial =
"""
// <auto-generated/>
#nullable enable annotations

using System;
using System.Linq;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace Tests.SmartSelector.Models;

public partial class UserDetails
{
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    private static Func<User, UserDetails>? selectUserFunc;

    /// <summary>Projection expression that creates a new <see cref="UserDetails"/> from a <see cref="User"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    public static Expression<Func<User, UserDetails>> SelectUserExpression { get; } = a => new UserDetails
    {
        Id = a.Id,
        Name = a.Name,
        Status = (StatusDetails)a.Status,
        LastLogin = a.LastLogin.HasValue ? a.LastLogin.Value : default,
        Specialization = a.Specialization.HasValue ? (UserSpecializationDetails)a.Specialization.Value : default
    };

    /// <summary>Creates a new <see cref="UserDetails"/> projected from a <see cref="User"/> instance.</summary>
    /// <param name="user">The source instance to project.</param>
    /// <returns>A new <see cref="UserDetails"/> instance.</returns>
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    public static UserDetails From(User user) => (selectUserFunc ??= SelectUserExpression.Compile())(user);
}

""";

    public const string ExpectedExtension =
"""
// <auto-generated/>
#nullable enable annotations

using System;
using System.Linq;
using System.Collections.Generic;

namespace Tests.SmartSelector.Models;

/// <summary>Generated extension methods to project <see cref="User"/> instances into <see cref="UserDetails"/> instances.</summary>
[global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
public static class UserDetails_Extensions
{
    /// <summary>Projects the <see cref="User"/> query into <see cref="UserDetails"/>.</summary>
    /// <param name="query">The source query.</param>
    /// <returns>An <see cref="IQueryable{T}"/> of <see cref="UserDetails"/>.</returns>
    public static IQueryable<UserDetails> SelectUserDetails(this IQueryable<User> query)
    {
        return query.Select(UserDetails.SelectUserExpression);
    }

    /// <summary>Projects the <see cref="User"/> items into <see cref="UserDetails"/>.</summary>
    /// <param name="enumerable">The source items.</param>
    /// <returns>An <see cref="IEnumerable{T}"/> of <see cref="UserDetails"/>.</returns>
    public static IEnumerable<UserDetails> SelectUserDetails(this IEnumerable<User> enumerable)
    {
        return enumerable.Select(UserDetails.From);
    }

    /// <summary>Projects a <see cref="User"/> instance into a new <see cref="UserDetails"/>.</summary>
    /// <param name="user">The source instance to project.</param>
    /// <returns>A new <see cref="UserDetails"/> instance.</returns>
    public static UserDetails ToUserDetails(this User user) => UserDetails.From(user);
}

""";
}
