using FluentAssertions;
using Microsoft.CodeAnalysis;

namespace RoyalCode.SmartSelector.Tests.Tests;

public partial class NullableAndCastSelectorTests
{
    [Fact]
    public void Select_Nulls_Enums_Cast()
    {
        var result = Util.CompileAndAssert(Code.Types);

        var generatedInterface = result.GeneratedSource("Tests.SmartSelector.Models.EnumNullsTypeDto.AutoSelect.g.cs");
        generatedInterface.Should().Be(Code.ExpectedPartial);
    }
}

file static class Code
{
    public const string Types =
"""
using RoyalCode.SmartSelector;

namespace Tests.SmartSelector.Models;

public enum NullsKind
{
    None,
    Nullable,
    NonNullable
}

public class EnumNulls
{
    public NullsKind Value1 { get; set; } = default!;
    public NullsKind Value2 { get; set; } = default!;
    public NullsKind? Value3 { get; set; }
    public NullsKind? Value4 { get; set; }
}

public enum NullsType
{
    None,
    Nullable,
    NonNullable
}

[AutoSelect<EnumNulls>]
public partial class EnumNullsTypeDto
{
    public NullsType Value1 { get; set; } = default!;
    public NullsType? Value2 { get; set; }
    public NullsType Value3 { get; set; } = default!;
    public NullsType? Value4 { get; set; }
}

""";

    public const string ExpectedPartial =
"""
// <auto-generated/>
#nullable enable annotations

using System;
using System.Linq;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace Tests.SmartSelector.Models;

public partial class EnumNullsTypeDto
{
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    private static Func<EnumNulls, EnumNullsTypeDto>? selectEnumNullsFunc;

    /// <summary>Projection expression that creates a new <see cref="EnumNullsTypeDto"/> from a <see cref="EnumNulls"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    public static Expression<Func<EnumNulls, EnumNullsTypeDto>> SelectEnumNullsExpression { get; } = a => new EnumNullsTypeDto
    {
        Value1 = (NullsType)a.Value1,
        Value2 = (NullsType?)a.Value2,
        Value3 = a.Value3.HasValue ? (NullsType)a.Value3.Value : default,
        Value4 = (NullsType?)a.Value4
    };

    /// <summary>Creates a new <see cref="EnumNullsTypeDto"/> projected from a <see cref="EnumNulls"/> instance.</summary>
    /// <param name="enumNulls">The source instance to project.</param>
    /// <returns>A new <see cref="EnumNullsTypeDto"/> instance.</returns>
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    public static EnumNullsTypeDto From(EnumNulls enumNulls) => (selectEnumNullsFunc ??= SelectEnumNullsExpression.Compile())(enumNulls);
}

""";
}
