using FluentAssertions;
using Microsoft.CodeAnalysis;

namespace RoyalCode.SmartSelector.Tests.Tests;

public partial class NullableAndCastSelectorTests
{
    [Fact]
    public void Select_Nulls_Collections()
    {
        var result = Util.CompileAndAssert(Code.Types);

        var generatedInterface = result.GeneratedSource("Tests.SmartSelector.Models.CollectionsNullsDto.AutoSelect.g.cs");
        generatedInterface.Should().Be(Code.ExpectedPartial);
    }
}

file static class Code
{
    public const string Types =
"""
using RoyalCode.SmartSelector;
using System.Collections.Generic;

namespace Tests.SmartSelector.Models;

public class EnumerableNulls
{
    public IEnumerable<string> Value1 { get; set; } = default!;
    public IEnumerable<string> Value2 { get; set; } = default!;
    public IEnumerable<string>? Value3 { get; set; }
    public IEnumerable<string>? Value4 { get; set; }
}

[AutoSelect<EnumerableNulls>]
public partial class CollectionsNullsDto
{
    public ICollection<string> Value1 { get; set; } = default!;
    public ICollection<string>? Value2 { get; set; }
    public ICollection<string> Value3 { get; set; } = default!;
    public ICollection<string>? Value4 { get; set; }
}

""";

    public const string ExpectedPartial =
"""
// <auto-generated/>
#nullable enable annotations

using System;
using System.Linq;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace Tests.SmartSelector.Models;

public partial class CollectionsNullsDto
{
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    private static Func<EnumerableNulls, CollectionsNullsDto>? selectEnumerableNullsFunc;

    /// <summary>Projection expression that creates a new <see cref="CollectionsNullsDto"/> from a <see cref="EnumerableNulls"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    public static Expression<Func<EnumerableNulls, CollectionsNullsDto>> SelectEnumerableNullsExpression { get; } = a => new CollectionsNullsDto
    {
        Value1 = a.Value1.ToList(),
        Value2 = a.Value2.ToList(),
        Value3 = a.Value3.ToList(),
        Value4 = a.Value4.ToList()
    };

    /// <summary>Creates a new <see cref="CollectionsNullsDto"/> projected from a <see cref="EnumerableNulls"/> instance.</summary>
    /// <param name="enumerableNulls">The source instance to project.</param>
    /// <returns>A new <see cref="CollectionsNullsDto"/> instance.</returns>
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    public static CollectionsNullsDto From(EnumerableNulls enumerableNulls) => (selectEnumerableNullsFunc ??= SelectEnumerableNullsExpression.Compile())(enumerableNulls);
}

""";
}
