using FluentAssertions;
using Microsoft.CodeAnalysis;

namespace RoyalCode.SmartSelector.Tests.Tests;

public partial class SelectTests
{
    [Fact]
    public void Select_PostAndCommentsDetails()
    {
        var result = Util.CompileAndAssert(Code.Types);

        var generatedInterface = result.GeneratedSource("Tests.SmartSelector.Models.PostAndCommentsDetails.AutoSelect.g.cs");
        generatedInterface.Should().Be(Code.ExpectedPartial);
    }
}

file static class Code
{
    public const string Types =
"""
using RoyalCode.SmartSelector;
using System.Collections.Generic;

namespace Tests.SmartSelector.Models;

#nullable disable // poco

public abstract class Entity<TId>
{
    public TId Id { get; protected set; }
}

public class Blog : Entity<string>
{
    public string Title { get; set; }
    public string Content { get; set; }
    public Author Author { get; set; }
    public ICollection<Post> Posts { get; set; } = [];
}

public class Author : Entity<Guid>
{
    public string Name { get; set; }
    public string Bio { get; set; }
    public User User { get; set; }
}

public class User : Entity<Guid>
{
    public User(string name)
    {
        Name = name;
        Status = Status.Active;
    }

    public string Name { get; set; }

    public Status Status { get; set; }

    public DateTimeOffset? LastLogin { get; set; }
}

public enum Status
{
    Active,
    Inactive,
    Blocked,
    Suspended,
}

public class Post : Entity<Guid>
{
    public string Title { get; set; }
    public string Content { get; set; }
    public Author Author { get; set; }
    public Blog Blog { get; set; }
    public ICollection<Comment> Comments { get; set; } = [];
}

public class Comment : Entity<Guid>
{
    public string Content { get; set; }
    public Post Post { get; set; }
    public User Author { get; set; }
}

public partial class PostDetails
{
    public string Title { get; set; }
    public string Content { get; set; }
    public AuthorDetails Author { get; set; }
}

public partial class AuthorDetails
{
    public string Name { get; set; }
}

[AutoSelect<Post>]
public partial class PostAndCommentsDetails : PostDetails
{
    public IReadOnlyList<CommentDetails> Comments { get; set; } = [];
}

public partial class CommentDetails
{
    public string Content { get; set; }
    public string AuthorName { get; set; }
}

""";
    public const string ExpectedPartial =
"""
// <auto-generated/>
#nullable enable annotations

using System;
using System.Linq;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace Tests.SmartSelector.Models;

public partial class PostAndCommentsDetails
{
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    private static Func<Post, PostAndCommentsDetails>? selectPostFunc;

    /// <summary>Projection expression that creates a new <see cref="PostAndCommentsDetails"/> from a <see cref="Post"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    public static Expression<Func<Post, PostAndCommentsDetails>> SelectPostExpression { get; } = a => new PostAndCommentsDetails
    {
        Title = a.Title,
        Content = a.Content,
        Author = new AuthorDetails
        {
            Name = a.Author.Name
        },
        Comments = a.Comments.Select(b => new CommentDetails
        {
            Content = b.Content,
            AuthorName = b.Author.Name
        }).ToList()
    };

    /// <summary>Creates a new <see cref="PostAndCommentsDetails"/> projected from a <see cref="Post"/> instance.</summary>
    /// <param name="post">The source instance to project.</param>
    /// <returns>A new <see cref="PostAndCommentsDetails"/> instance.</returns>
    [global::System.CodeDom.Compiler.GeneratedCode("RoyalCode.SmartSelector.Generators", "0.5.0.0")]
    public static PostAndCommentsDetails From(Post post) => (selectPostFunc ??= SelectPostExpression.Compile())(post);
}

""";
}

